version: "3.9"

services:
  db:
    init: true
    container_name:
      db
    build: 
      context: ./project/sql
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - transnet
    # volumes:
    #   - "transcendance_db:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  back:
    init: true
    ports:
      - "3000:3000"
    container_name:
      back
    depends_on:
      - db
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      APP_ID: ${APP_ID}
      APP_SECRET: ${APP_SECRET}
      APP_REDIRECT_URI: ${APP_REDIRECT_URI}
      JWT_SECRET : ${JWT_SECRET}
    build:
      context: ./project/back
    networks:
      - transnet
    restart: unless-stopped

  front:
    init: true
    container_name:
      front
    depends_on:
      - back
    build:
      context: ./project/front
    networks:
      - transnet
    ports:
      - "8080:8080"

  # phpmyadmin: # TODO: remove phpmyadmin
  #   depends_on:
  #     - db
  #   image: phpmyadmin/phpmyadmin
  #   container_name:
  #     phpmyadmin
  #   networks:
  #     - transnet
  #   environment:
  #     PMA_HOST: db
  #     PMA_USER: transcendence
  #     PMA_PASSWORD: 8m*rRX3ubgX4di0PSQA46k2Zf2JlUx
  #     PMA_PORT: 33065432
  #     PMA_ARBITRARY: 1
  #   restart: always
  #   ports:
  #     - 8081:80

  # pgadmin:
  # # TODO: remove pgadmin
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "5050:81"
  #   networks:
  #     - transnet

# volumes:
#   temp:
#     driver: local
#     driver_opts:
#       type: none
#       device: ./tempfront
#       o: bind

#   transcendance_db:
#     driver: local
#     driver_opts:
#       type: none
#       device: ./device
#       o: bind
#./project/front/ts

volumes:
  temp:
  transcendance_db:

networks:
  transnet:
    driver: bridge

