version: "3.9"

services:
  db:
    container_name:
      db
    build: 
      context: ./project/sql
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${BACK_SQL_PASSWORD}
      POSTGRES_USER: ${BACK_SQL_NAME}
      POSTGRES_DB: ${DATA_BASE_NAME}
    networks:
      - transnet
    volumes:
      - "transvolu:/var/lib/postgresql/data"

  back:
    container_name:
      back
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: ${BACK_SQL_PASSWORD}
      POSTGRES_USER: ${BACK_SQL_NAME}
      POSTGRES_DB: ${DATA_BASE_NAME}
    build:
      context: ./project/back
    networks:
      - transnet

  front:
    container_name:
      front
    depends_on:
      - back
    build:
      context: ./project/front
    networks:
      - transnet

volumes:
  transvolu:
    driver: local
    driver_opts:
      type: none
      device: ./device
      o: bind

networks:
  transnet:
    driver: bridge