services:
  db:
    init: true
    container_name: db
    build:
      context: ./project/sql
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db_dev
    networks:
      - transnet
    ports:
      - "5432:5432"

  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    ports:
      - "3215:8080"
    networks:
      - transnet

  back:
    env_file:
      - project/back/.env
    init: true
    container_name: back
    ports:
      - "3000:3000"
    depends_on:
      - db
    build:
      context: ./project/back
    networks:
      - transnet
    restart: unless-stopped

volumes:
  temp:
  transcendance_db:

networks:
  transnet:
    driver: bridge
