version: "3.9"

services:
  db:
    container_name:
      postgres
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${BACK_SQL_PASSWORD}
      POSTGRES_USER: ${BACK_SQL_NAME}
      POSTGRES_DB: ${DATA_BASE_NAME}
    networks:
      - transnet
    volumes:
      - "mariadb_vol:${MYSQL_VOLUME}"

  back:
    container_name:
      back
    depends_on:
      db
    environment:
      POSTGRES_PASSWORD: ${BACK_SQL_PASSWORD}
      POSTGRES_USER: ${BACK_SQL_NAME}
      POSTGRES_DB: ${DATA_BASE_NAME}
    build:
      context: project/front
    networks:
      - transnet
    


  front:
    container_name:
      front
    depends_on:
      back
    networks:
      - transnet


volumes:
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/ajossera/data/wordpress
      o: bind
  mariadb_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/ajossera/data/mariadb
      o: bind


networks:
  inception:
    driver: bridge